channels:
- conda-forge
dependencies:
- python=3.10.11
- pip<=23.0.1
- pip:
  - mlflow==2.10.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.0
  - pyyaml==6.0.1
  - scipy==1.12.0
  - torch-geometric==2.4.0
  - torch==2.2.0
name: mlflow-env
