channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=23.2.1
- pip:
  - mlflow==2.11.0
  - cloudpickle==3.0.0
  - jinja2==3.1.3
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - pyyaml==6.0.1
  - scipy==1.12.0
  - torch-geometric==2.5.0
  - torch==2.2.1
name: mlflow-env
